apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: colorpixapi
  name: colorpixapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: colorpixapi
    spec:
      containers:
      - env:
        - name: GET_HOST_FROM
          value: dns
        image: samanthreddys/colorpixapi:v1
        name: colorpixapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: ./go/src/colorpixapi
          name: colorpixapi-claim0
      hostname: colorpixapi
      restartPolicy: Always
      volumes:
      - name: colorpixapi-claim0
        persistentVolumeClaim:
          claimName: colorpixapi-claim0
status: {}
